on:
  push:
    branches:
    - master

jobs:
  build:
    name: build jar file
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
          ref: dev
          fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: build jar
      run: |
        ls
        cd java_src/bin
        jar cfmv ../../Coincidix.jar ../MANIFEST.MF main/*.class ../data

    - name: Commit files
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add Coincidix.jar
        git commit -a -m "latest release"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.head_ref }}


      
